### ISSUE TITLE
"Recent updates" tab empty in Fx47 (but not in SeaMonkey)

### ISSUE THREAD

**Issue by tonymec** [Infocatcher/Addons_Recent_Updates#4]
UA:"Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0" (en-US) ID:20160208030244 CSet:ac338559876df7b2e81388f2aac28d2e95ceb5ff

Add-ons Recent Updates 0.1.6.1-signed

The "Recent Updates" tab of about:addons is empty (others aren't). Trying other numbers of days (366, 200, 90) doesn't change anything. Disabling just this extension restores the recent updates contents.

Works with 366 days and the same add-on release in the following SeaMonkey build:
UA:"Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 SeaMonkey/2.44a1"
ID:20160208023510 en-US
c-c:4a60c0ffe9af0b68a82a6601c121e251863235e5
m-c:1cfe34ea394c66d7fa2c6dc366b05ab00e919113

**Comment by Infocatcher** [comment]
This is due to #3, I think.

**Comment by tonymec** [comment]
Hm, yes, the recently fixed [bug 1090880](https://bugzilla.mozilla.org/show_bug.cgi?id=1090880) mentioned in #3 is only about removing FUEL from Firefox, not its backends from Toolkit, so as long as SMILE remains in SeaMonkey it won't be affected.

**Comment by Infocatcher** [comment]
Should be fixed now:
https://addons.mozilla.org/addon/addons-recent-updates/versions/0.1.7

**Comment by tonymec** [comment]
After I click "Check for Updates" in the rolldown widget, Addons Recent Updates 0.1.7 is found, and after restarting it works as expected AFAICT on both Firefox and Seamonkey (both with Toolkit 47.0a1 on Linux64). :smiley:
