### ISSUE TITLE
Doesn't work in Firefox 55.0a1+ due to syntax error

### ISSUE THREAD

**Issue by Infocatcher** [Infocatcher/Addons_Recent_Updates#5]
Reported here: https://addons.mozilla.org/ru/firefox/addon/addons-recent-updates/reviews/847398/
Source code was changed:
chrome://mozapps/content/extensions/extensions.js
```js
var gUpdatesView = {
  ...
  _showRecentUpdates(aRequest) {
    AddonManager.getAllAddons((aAddonsList) => {
      ...
    });
  },
```
And `eval("gUpdatesView._showRecentUpdates = " + origShowRecentUpdates.toString());` doesn't work.
```
Error: SyntaxError: missing ; before statement
Source file: chrome://addonsrecentupdates/content/addonsOverlay.xul
Line: 1, Column: 63
Source code:
datesView._showRecentUpdates = _showRecentUpdates(aRequest) {
```

**Comment by tonymec** [comment]
AFAICT, it works. Install as follows (on Linux; for Windows the procedure is "similar but slightly different"):
1. Clone to your HD: I did it as follows:
1a. mkdir -pv ~/.build/infocatcher
1b. cd ~/.build/infocatcher
1c. git clone -v https://github.com/Infocatcher/Addons_Recent_Updates.git
2. cd Addons_Recent_Updates
3. chmod -c a+x make.sh
4. ./make.sh
-- A new xpi is created in the current directory.
5. Install that xpi (by means of the drop-down near top right of the Addons Manager)
6. Restart the browser.

**Comment by Infocatcher** [comment]
Signed "beta" version: https://addons.mozilla.org/addon/addons-recent-updates/versions/0.1.8pre
Release (not yet available, awaiting for review): https://addons.mozilla.org/addon/addons-recent-updates/versions/0.1.8 (Queue Position: 279 of 279, may be VERY slow...)

**Comment by tonymec** [comment]
I don't have access to this version 0.1.8 "release" at AMO ("We're sorry, but we can't find what you're looking for.") and I can only get at the 0.1.8pre by clicking the URL — otherwise the newest build I see at AMO is 0.1.7 — but a new commit appeared a few hours ago on my git clone (tagged 0.1.8) and I installed it as a matter of course. No issues so far ;-)

Signature checking seems disabled on SeaMonkey — ah, yes:

    xpinstall.signatures.required    default    boolean    false

**Comment by Infocatcher** [comment]
> I don't have access to this version 0.1.8 "release" at AMO

Yes, now will appears (for public) only after approval from AMO reviewers.
And this may take very long time (month or more): the review queue is very long.
